M48
; DRILL file {KiCad 9.0.7-1.fc43} date 2026-01-31T17:59:18-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-31T17:59:18-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-1.fc43
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.150
%
G90
G05
T1
X137.984Y-111.34
X139.0Y-106.26
X140.016Y-111.34
T2
X135.0Y-97.5
X135.0Y-102.5
M30
